### ISSUE TITLE
foreach problem

### ISSUE THREAD

**Issue by abiani** [openix/php2twig#1]
When put: 
`<?php` foreach ($product['options'] as $option) { ?>

`<?php` } ?>
TO
{% for option in product %}

**Comment by abiani** [comment]
`<?php` if (!empty($product['options'])) { ?>
				`<?php` foreach ($product['options'] as $option) { ?>
					<tr>
						<td class="text-left"> </td>
						<td class="text-left"><span class="help">   - `<?php` echo $option['name']; ?>: `<?php` echo $option['value']; ?> - `<?php` echo $option['name_2']; ?>: `<?php` echo $option['value_2']; ?></span></td>
						<td class="text-left"> </td>
						<td class="text-right"><span `class="help"><?php` echo $option['quantity']; ?></span></td>
						<td class="text-right"><span `class="help"><?php` echo $option['total']; ?></span></td>
					</tr>
				`<?php` } ?>
          `<?php` } ?>
TO

{% if product.options %} 
				{% for option in product %} 
					<tr>
						<td class="text-left"> </td>
						<td class="text-left"><span class="help">   - {{ option.name }} : {{ option.value }}  - {{ option.name_2 }} : {{ option.value_2 }} </span></td>
						<td class="text-left"> </td>
						<td class="text-right"><span class="help">{{ option.quantity }} </span></td>
						<td class="text-right"><span class="help">{{ option.total }} </span></td>
					</tr>
				{% endif %}

**Comment by eka7a** [comment]
@abiani Hi,
Thank you feedback. We will check.

**Comment by eka7a** [comment]
@abiani fixed foreach end
